### ISSUE TITLE
ModuleNotFoundError: No module named 'string_grouper'

### ISSUE THREAD

**Issue by neongreen13** [Bergvca/string_grouper#7] opened 2020-05-10 16:38 UTC
Hi! Great package by the way, thanks for creating this code! I love the concept.

I used string_grouper two weeks ago on another project and loved it. I tried installing again yesterday on another computer and it says there is no module. Did something change or update? Thanks for your help!

**Comment by rhurley46** [comment] 2020-05-11 13:05
Having the same issue as @neongreen13 when trying to install on a Google Colab notebook. Is there a fix for this yet?

**Comment by Bergvca** [comment] 2020-05-11 13:08
Strange, no changes were made to the pypi module in the last months. Will check later. In the meanwhile, did you try installing from github?

**Comment by rhurley46** [comment] 2020-05-11 13:11
Thanks for getting back to us so promptly, @Bergvca.

I'm installing from github now and will report if that is successful or not.

**Comment by neongreen13** [comment] 2020-05-11 14:24
Yes thanks for the quick reply @Bergvca . Just tried to install from github. Here is the error:

ERROR: Cannot unpack file /tmp/pip-unpack-n6z2ltmm/string_grouper.py (downloaded from /tmp/pip-req-build-kk18od7z, content-type: text/html; charset=utf-8); cannot detect archive format
ERROR: Cannot determine archive format of /tmp/pip-req-build-kk18od7z

Thanks again for your help!

**Comment by Bergvca** [comment] 2020-05-11 19:55
Hi guys, 

I'm not able to reproduce this under Ubuntu 19.10 and Python 3.7.3. @rhurley46 - I'm not familiar with Google Colab but can imagine it doesn't run all custom libraries (especially since this one compiles C code).  @neongreen13 what environment are you running this in?

**Comment by neongreen13** [comment] 2020-05-12 14:12
@Bergvca I am working in Ubuntu. perhaps that's the issue, I switched devices. i used it last on a window computer. i can use it there in the meantime. thanks again for your help!

**Comment by gw00207** [comment] 2020-05-17 16:10
I'm also having this issue, I can `import string_grouper` from ipython, but starting a jupyter notebook and importing there fails.

**Closed** 2020-07-15 18:45 UTC
